USE [GamesWorkshopDb]
GO
SET IDENTITY_INSERT [dbo].[Products] ON 

INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (1, N'Possesed', N'Possessed are bestial slaughter incarnate – Astartes warriors merged with fell daemons of the Chaos Gods in a blasphemous union. Warped and mutated by their empyric parasites, the armoured forms of the Possessed flow like wax, shrugging off lethal blows as they manifest talons, snapping maws, and vestigial wings to unleash an unholy orgy of bloodshed.

This multipart plastic kit builds five Possessed, monstrous close combat fighters who bear a host of repulsive mutations, from claws and tentacles to bladed limbs. Each model comes with a variety of cosmetic choices – including alternative heads, daemonic limbs, interchangeable backpacks, and other accessories – to ensure that no two models look the same, even within larger units or multiple squads of half-daemon monstrosities. The kit also includes an optional Chaos icon, for a Possessed Champion to invoke the dark blessings of the Ruinous Powers.

This set comprises 56 plastic components and is supplied with 5x Citadel 40mm Round Bases. These miniatures are supplied unpainted and require assembly – we recommend using Citadel Plastic Glue and Citadel paints.', N'Fearsome Elites for Chaos Space Marines
Builds five Possessed, with a variety of cosmetic options for creating uniquely profane half-daemon Astartes
Shred your foes in melee with lashing tentacles, snapping claws, and bladed limbs', 45, 20, 2, CAST(N'2022-05-19' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102140_CSMPossessedLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102140_CSMPossessedFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102140_CSMPossessedSprue1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120102140_CSMPossessedOTT3360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120102140_CSMPossessedOTT2360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102140_CSMPossessedStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (2, N'Mekboy Workshop', N'All Mekboyz can perform battlefield repairs using no more than a weighty wrench-hammer, a sack of nails and a healthy dose of gumption, but most do their best work in the comfortably anarchic surrounds of their own workshop. Meks are more than capable of cobbling together a workspace from whatever is lying about, with rudimentary workshops springing up from battlefield wreckage even while the bullets are still flying. Greenskin vehicles roar toward such teetering structures, their crews throwing sacks of teef at the resident Mek – he and his crew get to work immediately, sending the Ork customers on their way with snazzier guns, souped-up engines and extra armour plates.

This multipart plastic kit contains the components necessary to assemble a Mekboy Workshop. Constructed from metal beams which the industrious Mekboy has salvaged from the clamour of battle around him, the Workshop features a large workbench covered in the gubbinz of his craft – a wall-mounted toolset, an enormous drill, a box of spanners and a vice – and a ton of spare parts. A kustom force field generator, bits of steering wheel, buzzsaw blades; it might look like a random assortment, but the Mekboy who owns it knows exactly where each piece he needs is. A reinforced beam is attached to this workspace at a right angle – a large engine block is hanging from a length of chain, ready for repair or installation, with a large grabbin’ klaw which can be modelled facing in any direction you like. Included are 3 barricades and 3 piles of scrap, which can be placed around the Workshop in any way you like, and the whole kit is compatible with the STC Ryza-pattern Ruins set – build your own kustom sprawling mess!

This kit is supplied as 36 components.', N'An especially Orky scenery piece, the dominion of a crazed Mekboy
Adds more speed, more rivets and more dakka to Ork vehicles in-game
Complete with 3 sets of barricades and a load of scrap!', 45, 100, 4, CAST(N'2022-03-18' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103061_OrkMekWorkshop01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120103109_MekboyWorkshopOTT360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103061_OrkMekWorkshop02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103061_OrkMekWorkshop03.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103061_OrkMekWorkshopTerrain.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103061_OrkMekWorkshop05.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (3, N'Combat Patrol: Chaos Daemons', N'The daemonic servants of Khorne spill from the madness of the warp to corrupt and slaughter, the very battlefield contorting at the touch of Chaos. Gore-drenched Bloodletters hack heads from shoulders, led into the material plane by Bloodmasters, the greatest of their ravenous kind. Mounted atop the infernal engine-beasts known as Juggernauts, a charge by merciless Bloodcrushers breaks the most stalwart resistance, while tireless Flesh Hounds pursue any who flee across time and space.

Claim skulls for Khorne with Combat Patrol: Chaos Daemons! This boxed set provides you with all the units you need to start your collection or reinforce an existing army. The contents of this set have been specifically chosen to provide you with a Chaos Daemons force ideal for Combat Patrol-sized games – approximately 25 Power Level''s worth of models – and will also save you money compared to buying the contents individually.

This set includes the following multipart plastic models:
– 1x Bloodmaster
– 3x Bloodcrushers
– 10x Flesh Hounds
– 20x Bloodletters

All models are supplied with their appropriate bases.

These miniatures are supplied unpainted and require assembly – we recommend using Citadel Plastic Glue and Citadel paints.', N'A bloody host of Khornate Chaos Daemons ideal for starting or expanding an army
A Combat Patrol-sized force in a box, designed to save you money
Contains 34 multipart plastic miniatures', 120, 15, 2, CAST(N'2022-04-19' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120115002_ChaosDaemonsCombatPatrolLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120115002_CDAECPFeature1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120115002_CDAECPFeature2.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120115002_CDAECPFeature3.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120115002_ChaosDaemonsCombatPatrolSprue02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120115002_ChaosDaemonsCombatPatrolSprue03.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (5, N'Khorne Lord of Skulls', N'This massive Daemon Engine of Khorne is built in hell forges with the sole purpose of killing, maiming and burning its enemies until they are no more than a sticky paste under its mighty tracks.

Measuring almost 6” tall, and just over 7” in length, this huge kit comes with a number of assembly options. For starters you get to equip the right arm with a massive Great Cleaver of Khorne. Alongside this you have the choice of whether to equip the left arm with the infantry shredding Hades Gatling Gun or the aptly named Skull Hurler. You also have the option to make any of the three belly guns, as detailed in the Apocalypse rulebook, choosing either the Gorestorm Cannon, Daemongore Cannon,or the Ichor Cannon. Also included are two heads, so you can decide whether you want a fully enclosed helm, or whether you’d rather stare into the cold, dead eyes of the Daemon Engine itself.

This plastic kit contains 99 components and 2 Transfer Sheets with which to make a Khorne Lord of Skulls.

This kit comes supplied unpainted and requires assembly - we recommend using Citadel Plastic Glue and Citadel Paints.', NULL, 130, 50, 2, CAST(N'2022-11-10' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102041_LordofSkulls01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102041_LordofSkulls03.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102041_LordofSkulls05.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102041_LordofSkulls02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120102041_LordofSkulls360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120102041_LordofSkullsSprue02.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (6, N'Space Marines: Honoured of the Chapter', N'As the Indomitus Crusade spreads across the galaxy, the Primaris Space Marines fight battle after battle, becoming hardened veterans of their Chapters. From the mightiest heroes to the staunchest battle-brothers, each is an honoured warrior whose deeds are legend.

This set allows you to add new HQ, Elites, and Heavy Support choices to your Space Marines army. A Primaris Chaplain will enhance the fighting strength of the warriors around him, while a Bladeguard Ancient inspires them to fight on against any odds. The Judiciar can be found in the thick of combat, his great blade cleaving enemy heads. Bladeguard Veterans will join him at the vanguard, their storm shields making them an immovable bulwark. Finally, Eradicators will target the enemy''s heaviest armour and bring it down in volleys of melta fire.

This 64-piece plastic kit builds 9 Space Marines models:

– 1x Primaris Chaplain
– 1x Judiciar
– 1x Bladeguard Ancient
– 3x Bladeguard Veterans
– 3x Eradicators

Both the Bladeguard Veterans and Eradicators include a Sergeant. The set also includes nine 40mm round bases.

The models in this set are push-fit and can be assembled without glue. Rules for them can be found in Codex: Space Marines.', N'Reinforcements for your Space Marines army
Includes three Characters and two squads
Available for the first time outside the Indomitus box', 130, 40, 0, CAST(N'2022-09-12' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101353_HonouredoftheChapterLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120101353_SMHonouredOfTheChapterOTT8360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101353_HonouredoftheChapterFeature2.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101353_HonouredoftheChapterFeature1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101353_HonouredoftheChapterVeteransFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101353_HonouredoftheChapterSprue.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (11, N'Manticore', N'The Imperial Guard Manticore Rocket Launcher is an incredibly destructive war machines. It launches a salvo of rockets, each of which disperses into multiple warheads.

The Manticore Rocket Launcher is an impressive addition to an Imperial Guard collection. Most notable about it are the storm eagle rockets – four enormous rockets that sit atop the vehicle aimed upward, ready to unleash some hellish devastation below. The rest of the tank is a wall of metal: with panelling, rivets, heavy bolter, detailed treads and numerous fine details such as smoke launchers, searchlights and a communication device. The open hatch reveals a guardsman within.

This multi-part plastic box set contains 85 components and an Imperial Guard Transfer Sheet with which to make one Manticore Rocket Launcher or one Deathstrike Missile Launcher.

This kit is supplied unpainted and requires assembly - we recommend using Citadel Plastic Glue and Citadel Paints.', NULL, 45, 50, 1, CAST(N'2022-07-12' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120105049_ManticoreNEW01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120105049_Manticore360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120105049_IGManticoreDeathstrikeSprue1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120105049_IGManticoreDeathstrikeSprue2.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120105049_IGManticoreDeathstrikeXBox.jpg', NULL)
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (12, N'Deffkoptas', N'Most Orks take a dim view of muckin’ about in the sky, and would much rather go to war with their feet firmly on the ground. Deffkopta pilots are one of few exceptions, hurtling into the sky to spy out enemy forces for their warband, and give those same enemies a good strafing run or three in the meantime.

This kit builds three Deffkoptas – fast, ramshackle vehicles bristling with all sorts of crude but effective ork weaponry. These airborne brutes harrass their enemies with salvos of shells and high-powered explosions, before closing in to hack at their foes with hand weapons and deadly rotor blades. Two of the Deffkoptas are armed with kopta rokkits, spinning blades, a slugga, and stikkbombs, with the third trading its kopta rokkitz for a kustom mega-blasta and a big bomb.

This kit comprises 37 plastic components and is supplied with 3x Citadel 75mm Oval Bases. These miniatures are supplied unpainted and require assembly – we recommend using Citadel Plastic Glue and Citadel paints.', N'Rain death from above with these wacky whirlygigs
A Fast Attack option for any Waaagh!
Three Deffkoptas with an arsenal of aerial armaments', 50, 100, 3, CAST(N'2022-08-11' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103107_DeffkoptasLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103107_DeffkoptasFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103107_DeffkoptasScale.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103081_ORKCPSprue6.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120103081_CombatPatrolOrksOTT5360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103107_DeffkoptasStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (13, N'Biged Bossbunka', N'Ork warbosses are usually stationary for only two reasons. One is when they are giving an enemy – or an unlucky grot – a good hiding, and the other is when they are shouting at their Boyz to give the foe a good krumpin''. The Big''ed Bossbunka provides the perfect place to holler from given its bosspole, which is outfitted with a very loud PA system.

Constructed from the head of a repurposed Ork Gargant, the Big''ed Bossbunker gives your Warboss a way of directing the many rowdy Boyz under his command. If they misbehave, or if anyone attempts to unseat the Warboss, they will need to contend with a slew of shots from the Big''ed Bossbunker''s big shoota and the Gaze of Gork – a weapon constructed from a jet engine that has been bashed into one of the Gargant''s eyes.

This multi-part plastic kit is comprised of 27 components, and can be assembled into one Big''ed Bossbunker. This miniature is supplied unpainted and requires assembly – we recommend using Citadel Plastic Glue and Citadel paints.', N'A scrapped Ork Gargant head provides an excellent command post
Garrison a warboss and boys behind the scrap metal armour of this Fortification
Toast your enemies with the Gaze of Gork', 60, 500, 3, CAST(N'2022-05-13' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103082_BigEdBossBunkaLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103082_BigEdBossBunkaFeature1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103082_BigEdBossBunkaFeature2.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103082_BigEdBossBunkaSprue1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120103082_BigEdBossbunkaOTT360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103082_BigEdBossBunkaStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (14, N'KV128 Stormsurge', N'An absolute colossus of a machine, piloted by graduates of the Ves''oni''Vash, the KV128 Stormsurge is designed as an extreme heavy-weapons platform. Not as manoeuvrable as a Riptide, instead relying on thick armour and devastating loadouts, these hulking, squat ballistic suits are capable of changing the course of a battle in seconds with a decisive volley of astonishing firepower. Fitted with thrusters to counter recoil, bristling with pulse weaponry and missile pods, the Stormsurge is the T''au Empire''s Titan-killer.

The Stormsurge comes with a truly amazing amount of offensive firepower - two missile pod assemblies, a pulse driver cannon, a pulse ARC cannon, two ballistic burst cannons, two airbust frag projectors and twin-linked flamers!

This multi-part plastic kit contains all the components necessary to build one KV128 Stormsurge, ballistic suit of the T''au Empire. It includes an astonishing 171 components - four head options, two pilot assemblies, a reactor suite, two leg assemblies and two sets of stabilising thrusters! Various vents and assemblies can be modelled optionally closed or open, and the whole miniature has incredible posability. Includes one Citadel 170mm Oval base.', NULL, 60, 500, 3, CAST(N'2019-02-11' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120113036_TauKV128Stormsurge01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120113036_TauKV128Stormsurge02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120113071_StormsurgeFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120113036_TauKV128Stormsurge08.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120113036_TauKV128Stormsurge09.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120113071_StormsurgeStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (15, N'Gorkanaut', N'The Gorkanaut possesses all the unsubtle brutality of Gork along with a blocky silhouette that looms menacingly over friend and foe alike. Piloted by an Ork Nob, this hulking orkoid armoured war suit is the epitome of everything an Ork aspires to be: Massive, tough, loud and destructive.

The Gorkanaut’s main weapons are the deafening and deadly Deffstorm mega-shoota and the massive armoured Klaw of Gork (or possibly Mork). It is also armed with two twin-linked big shootas, two rokkit launchas and a skorcha.

This multi-part plastic kit contains all the components to make one Ork Gorkanaut or one Ork Morkanaunt and its packed with optional extras so you can add your own personalised finishing touches.  

Please note: the Ork Warboss featured in the image is for scale purposes only and is not included in this kit.', NULL, 105, 50, 3, CAST(N'2022-06-01' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103034_Gorkanaut01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120103088_OrksGorkanautOTT1360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103088_GorkanautFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103088_GorkanautScale.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103034_GorkanautSprue01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103088_MorkanautStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (16, N'Tesseract Vault', N'The Necron Tesseract Vault holds an imprisoned Transcendent C’tan, turning his powers into phenomenal weapons of mass destruction that can age its foes to dust, set acres ablaze, or trigger seismic shifts in the planetary crusts with a single gesture.

Standing just over a whopping 9” tall, and 10” wide, the Tesseract Vault dominates everything on the tabletop. And that’s without mounting it on its flying stand! There are two ways this kit can be put together: either as a Tesseract Vault or as an Obelisk.

If you assemble this as a Tesseract Vault you will need to use the Transcendent C’Tan miniature as part of the construction.

This plastic kit contains 57 components and a Necron Transfer Sheet. It comes supplied unpainted and requires assembly - we recommend using Citadel Plastic Glue and Citadel Paints.', NULL, 130, 75, 3, CAST(N'2022-01-01' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110026_NecronTesseract01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120110026_NecronTesseractVault360/01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110026_NecronTesseract02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110026_NecronTesseract04.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110026_NecronTesseract03.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110026_NecronTesseractBox01.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (18, N'Maugan Ra', N'Maugan Ra, also known as the Harvester of Souls, is the Phoenix Lord of the Dark Reapers – among the most grim and foreboding Aspects of the Asuryani. A master at killing from a distance, Maugan Ra wields the Maugetar. This scythe-like weapon fires mind-linked shuriken discs large enough to decapitate a swathe of foes before vanishing into nothingness. Should the enemy survive this barrage, they will meet a swift end on the curved edge of the Maugetar''s built-in reaping blade.

This kit builds Maugan Ra, the Harvester of Souls, armed with the deadly shuriken cannon Maugetar. Able to deliver the kiss of death from leagues away or cut down hordes of enemies like so much tall grass, Maugan Ra is a silent whirlwind of violence, the physical embodiment of the inevitability of death, and a powerful addition to any Aeldari army.

This set comprises 14 plastic components and is supplied with a Citadel 40mm Round Base. This miniature is supplied unpainted and requires assembly – we recommend using Citadel Plastic Glue and Citadel paints.', N'A legendary Phoenix Lord and HQ choice for your Aeldari forces
A supernaturally skilled combatant, deadly at all ranges
Cause your foes to cower in fear', 35, 55, 3, CAST(N'2022-08-11' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104069_AELMauganRaLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120104069_MauganRaOTT1360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104069_AELMauganRaFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104069_AELMauganRaSprue.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104069_AELMauganRaStock.jpg', NULL)
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (19, N'Avatar of Khaine', N'An Avatar of Khaine is an ancient deity incarnate – a burning shard of Khaela Mensha Khaine, the Bloody-Handed God of the Aeldari. Awakened for battle, he marches through enemy fire without breaking stride, laughing cruelly as his weapon – the Wailing Doom – cleaves flesh and tastes the blood of his foes with each strike. The Avatar''s mere presence incites a merciless rage in the Asuryani around him, his fearsome aura eradicating fear or hesitation in favour of a nigh insatiable murderlust. In these moments, the Aeldari seem transformed into a vision of the glorious and terrible conquerors who once ruled the galaxy.

This kit builds one Avatar of Khaine, who can be constructed with a choice of three different heads – a classic helmet with plume and headdress, a more martial helm with an ornate crest, or a bare head with a wild mane and flowing topknot. The Avatar''s divine weapon, the Wailing Doom, can also be built in one of three forms – a gigantic sword, a vicious axe, or a sweeping spear, each marked with eldritch runes of power.

This set comprises 53 plastic components and is supplied with 1x 80mm Citadel round base. This miniature is supplied unpainted and requires assembly – we recommend using Citadel Plastic Glue and Citadel paints', N'A monstrously powerful HQ choice for your Aeldari army
Bring ruin to your foes with the blazing embodiment of a shattered god
Your choice of three heads and three cosmetic variant weapons', 80, 50, 3, CAST(N'2022-10-12' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104072_AELAvatarofKhaineLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120104072_AvatarOfKhainOTT360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104072_AELAvatarofKhaineFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104072_AELAvatarofKhaineScale.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104072_AeldariAvatarOfKhainSprue.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120104072_AELAvatarofKhaineStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (20, N'Mozrog Skragbad', N'There are few Orks alive who are tougher or more belligerent than Mozrog Skragbad. A beast hunter of infamy, Mozrog once spent many days in self-imposed exile, hunting the most dangerous beasts he could find. One such monster nearly got the better of him, eating him alive, but Mozrog is nothing if not pugnacious – clawing his way out, he returned to his tribe to be patched up with all manner of bionic bits. In battle, he rides the unmissable pale-skinned squigosaur, Big Chompa – the only living creature as cantankerous as Mozrog himself.', N'The mightiest Warboss around – a great HQ choice for your Snakebite Beast Snagga Boyz
A fusion of Ork, machine, and squigosaur ready to inflict carnage on enemy lines
Can alternatively be built as a Beastboss on Squigosaur', 42.5, 70, 3, CAST(N'2022-01-09' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103075_MozrogLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103075_MozrogFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103075_MozrogSprue1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103075_MozrogSprue2.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103075_BeastbossSquigasaurLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103075_MozrogStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (22, N'Skitarii Rangers', N'Harnessing the energies of forge worlds within their curious weaponry, the Rangers of the Skitarii are implacable and relentless hunter-killers. For them, an engagement is not over until their enemy is destroyed - even if this means stalking them across galaxies and over decades.

Skitarii Rangers, featuring cowls and gasmasks, stalk their prey with galvanic rifles. Each trooper is sealed in heavy, industrialised Skitarii warplate, emblazoned with the symbol of the Adeptus Mechanicus, bristling with data-collecting sensors, antennae and environmental monitors. Mindful of the harsh terrain of Mars, their legs have been removed from the knees down, with bionic replacements lending each model an air of cold, cybernetic augmentation', NULL, 40, 111, 1, CAST(N'2022-03-14' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120116002_SkitariiRangers01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120116002_SkitariiRangers02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120116002_SkitariiRangers04.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120116002_SkitariiRangersSprue02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120116002_Ranger360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120116002_SkitariiRangers03.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (23, N'Adrax Agatone', N'Just as the duties of the Salamanders 3rd Company place an exceptional strain upon the noble and compassionate warriors who must discharge them, so an exceptional leader is required to ensure that this burden never becomes too great for even Vulkan''s sons to bear. Adrax Agatone is that leader.

Adrax Agatone is the anvil against which the enemies of the Salamanders break. Where he holds the line, the Salamanders fight with unstoppable determination. Agatone''s Arridian drakehide cloak protects him from all but the most potent weaponry, while he immolates them with Drakkis – his masterwork hand flamer – and delivers thunderous blows with his thunder hammer, Malleus Noctum.
', N'Lead your Salamanders with the noble 3rd Company Captain.
Shatter your enemies with Malleus Noctum…
…and burn them to ash with Drakkis.', 34, 50, 0, CAST(N'2022-05-29' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101259_SALAdraxAgatone01.jpg', NULL, N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101259_SALAdraxAgatone02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101293_AdraxAgatoneStock.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120101259_SalAdraxAgatone360/01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101259_SALAdraxAgatone04.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (24, N'Land Raider Redeemer', N'As the Crusader was a modification of the original Land Raider, so is the Redeemer an evolution of the Crusader design.



Like all mighty Space Marine tanks, the Land Raider Redeemer features incredibly solid armouring on all sides, and comes with metal panels, hatches, rivets and searchlight, all o which gives you a remarkably powerful addition for your Space Marine collection. The kit contains a jaw-dropping range of weaponry: two sets of hurricane bolters, a twin-linked assault cannon, a multi-melta, two flamestorm cannons, and frag assault launchers – all of which gives you plenty of options for personalisation.



This box set contains 124 components with which to make either a Land Raider Redeemer or a Land Raider Crusader.



This set is supplied unpainted and requires assembly - we recommend using Citadel Plastic Glue and Citadel Paints.', NULL, 85, 30, 0, CAST(N'2022-02-17' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101344_SMLandRaiderCrusaderandRedeemerLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101070_LandRaiderRedeemerNEW01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101070_LandRaiderRedeemerNEW02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101070_LandRaiderCrusader01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101070_LandRaiderCrusader08.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101070_LandRaiderCrusader03.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (25, N'Primaris Aggressors', N'Clad in heavy Gravis armour, Aggressor Squads advance on the foe as walking fortresses of ceramite. More mobile than some other Space Marines, they’re better able to negotiate rough ground, making them versatile troops; while they are often employed in specific circumstances or on certain terrain, Aggressor Squads are used as reserves to plug breaches in gun lines or to spearhead an advance. The range of their weaponry is not too long, but when they get close enough to open fire, the result is a sweeping fusillade of large-calibre bolter shells that can shatter enemy charges.

This multi-part plastic kit contains the components necessary to assemble a 3-man Primaris Aggressor Squad. Extremely heavily armoured, their silhouette is wider and chunkier than most Primaris Space Marines, due in no small part to the choice of auto boltstorm gauntlets or flamestorm gauntlets. There are three sets of each, with every weapon featuring pipes or belts that are fed from the enormous backpack. One set of flamestorm gauntlets features retracted barrels, as in close combat fists speak louder than flames… Should you choose the boltstorm gauntlets, the Aggressors can also take a fragstorm grenade launcher.

You have the option of assembling 3 Aggressors or 2 Aggressors and a Sergeant; a host of options are available either way. There are 6 heads for the standard Aggressors, with respirators on the mask of those using flamestorm gauntlets, and 2 more specific heads for the Sergeant. The flamestorm-wielding Aggressors have their own shoulder pads, featuring larger blast shielding to protect them from the immense operating temperatures of their weapons. Also included are reliquaries and purity seals, with special examples for Sergeants featuring extra skulls.

The Primaris Aggressors come as 107 components, and are supplied with 3 Citadel 40mm Round bases.', NULL, 42.5, 70, 0, CAST(N'2022-04-04' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101184_SpaceMarineAggressors01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101184_SpaceMarineAggressors02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101184_SpaceMarineAggressors05.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101184_SpaceMarineAggressors06.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101184_SpaceMarineAggressors07.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120101306_SMPrimarisAggressorsETB.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (26, N'Monolith', N'Nothing is so emblematic of Necron implacability as the Monolith. Like all Necron constructs, it is composed of living metal – a complex semi-sentient alloy that ripples and flows to repair damage in a blink of an eye. When combined with the vehicle’s slab-sided armour plates, this makes the Monolith an incredibly daunting opponent for any enemy.

Support your Necron army''s implacable advance with a Monolith. Not only can it provide covering fire with its gauss flux arcs, but it can also bring in reinforcements through its eternity gate. The gauss flux arcs can be replaced with death rays, while the kit also comes with a choice of eternity gate.

This 123-part plastic kit makes one Necron Monolith. It is supplied with a 160mm round Citadel base and a clear hover stand.', N'A destructive Lord of War choice for a Necron army
Obliterate your enemies with esoteric weapons
Summon reinforcements through the eternity gate', 140, 30, 3, CAST(N'2022-03-27' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110043_NECMonolithLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120110043_NecronsMonolithOTT1360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110043_NECMonolithFeature01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110043_NECMonolithFeature02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110043_NECMonolithSprue01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110043_NECMonolithStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (27, N'Lokhust Destroyer', N'Lokhust Destroyers are deranged agents of annihilation whose sole reason for existence is centred around an unshakeable yearning to quench the flames of life. A Destroyer cares not for borders or allegiances, nor does he make any distinction between the innocent and the damned – all life is his enemy, and all living creatures are his prey. To achieve this mission they will ruthlessly adapt, augment, or expunge any facet of their physical form if it will improve their mission of slaughter. Legs are removed in favour of repulsor platforms, arms are fused to the workings of gauss cannons, and even the Destroyer''s senses are reconfigured to allow them to track their targets more accurately. On the battlefield, these nihilistic warriors will shatter enemy formations with heavy fire, before swooping down upon the survivors to ensure that none survive.

This multi-part plastic boxed set contains 17 components with which to build one Lokhust Destroyer. This kit comes with two small flying stems, one large flying stand, and a Necrons transfer sheet. It is supplied unpainted and requires assembly – we recommend using Citadel Plastic Glue and Citadel Paints for the best results.', NULL, 21, 70, 3, CAST(N'2022-01-04' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110070_NecronDestroyerretoolLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120110070_NecronLokhustDestroyerOTT1360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110070_NecronDestroyerretoolFeature.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110070_NecronDestroyerretoolSprue.jpg', NULL, NULL)
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (28, N'Lokhust Heavy Destroyer', N'
The Destroyer Cults think nothing of sacrificing their physical forms to optimise themselves for slaughter. Lokhust Heavy Destroyers skim to battle upon repulsor-sled bodies, their upper limbs bound into gauss destructors or enmitic exterminators with which they decimate their foes with devastating blasts from afar.

Whether you''re looking to scythe through infantry or crack your enemy''s biggest tanks with ease, you''ll want a Lokhust Heavy Destroyer. This fast-moving gun platform pairs superbly with other Destroyer units or as a standalone for an army which just needs a little extra firepower.

This kit builds one Lokhust Heavy Destroyer. Push-fit construction means you won''t need any glue to build it, and the set comes with your choice of heads and deadly weapons. It is supplied in 33 plastic components and comes with a 60mm round base.', N'Destroy enemies at a distance
Push-fit - no need for glue!
Includes choice of head and weapon
This product may take up to 35 days to dispatch.', 27, 50, 3, CAST(N'2022-02-17' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110044_LokhustHeavyDestroyerLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120110044_NecronsLokhustHeavyDetroyerOTT1360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110044_LokhustHeavyDestroyerFeature01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110044_LokhustHeavyDestroyerFeature02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110044_LokhustHeavyDestroyerSprue01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120110044_LokhustHeavyDestroyerStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (29, N'Codex: Grey Knights', NULL, N'The essential guidebook for collectors of the Grey Knights
32 datasheets for all the warriors available to the elite warriors of the Ordo Malleus
Includes Relics, Stratagems, secondary objectives, Warlord Traits, Crusade rules, and loads more', 42, 150, 5, CAST(N'2022-04-04' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/60030107007_GKCodexStdEdLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/60030107007_GKCodexStdEdSpread1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/60030107007_GKCodexStdEdSpread2.jpg', NULL, NULL, NULL)
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (31, N'Castigator', NULL, N'A heavy support choice for Adepta Sororitas armies
Unleash the God-Emperor''s judgement upon your enemies
Choose between a brace of rapid-firing Castigator autocannons and the explosive Castigator battle cannon', 67.5, 50, 1, CAST(N'2022-03-01' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120108048_SoBCastigatorLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/threeSixty/99120108048_CastigorOTT1360/01-01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120108048_SoBCastigatorFeature01.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120108048_SoBCastigatorFeature02.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120108023_SoBExorcist05.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120108048_SoBCastigatorStock.jpg')
INSERT [dbo].[Products] ([Id], [Name], [Description], [Features], [Price], [Amount], [Category], [CreatedDate], [ImageSrc], [Image1], [Image2], [Image3], [Image4], [Image5]) VALUES (32, N'Ghazghkull Thraka', NULL, N'Lead your Waaagh! with the mighty Ghazghkull
Krump anyone who gets in your way
Supported by the legendary Makari', 55, 40, 3, CAST(N'2022-01-03' AS Date), N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103079_ThrakaLead.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103079_ThrakaFeature2.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103079_ThrakaFeature3.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103079_ThrakaFeature1.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103079_ThrakaSprue2.jpg', N'https://www.warhammer.com/app/resources/catalog/product/920x950/99120103079_ThrakaStock.jpg')
SET IDENTITY_INSERT [dbo].[Products] OFF
GO
