// <auto-generated />
using System;
using GamesWorshop.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesWorshop.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamesWorkshop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20,
                            Category = 2,
                            CreatedDate = new DateTime(2022, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Possessed are bestial slaughter incarnate – Astartes warriors merged with fell daemons of the Chaos Gods in a blasphemous union. Warped and mutated by their empyric parasites, the armoured forms of the Possessed flow like wax, shrugging off lethal blows as they manifest talons, snapping maws, and vestigial wings to unleash an unholy orgy of bloodshed.\r\n\r\nThis multipart plastic kit builds five Possessed, monstrous close combat fighters who bear a host of repulsive mutations, from claws and tentacles to bladed limbs. Each model comes with a variety of cosmetic choices – including alternative heads, daemonic limbs, interchangeable backpacks, and other accessories – to ensure that no two models look the same, even within larger units or multiple squads of half-daemon monstrosities. The kit also includes an optional Chaos icon, for a Possessed Champion to invoke the dark blessings of the Ruinous Powers.\r\n\r\nThis set comprises 56 plastic components and is supplied with 5x Citadel 40mm Round Bases. These miniatures are supplied unpainted and require assembly – we recommend using Citadel Plastic Glue and Citadel paints.",
                            Features = "Fearsome Elites for Chaos Space Marines\r\nBuilds five Possessed, with a variety of cosmetic options for creating uniquely profane half-daemon Astartes\r\nShred your foes in melee with lashing tentacles, snapping claws, and bladed limbs",
                            Image1 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120102140_CSMPossessedFeature.jpg",
                            Image2 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120102140_CSMPossessedSprue1.jpg",
                            Image3 = "https://www.games-workshop.com/resources/catalog/product/threeSixty/99120102140_CSMPossessedOTT3360/01-01.jpg",
                            Image4 = "https://www.games-workshop.com/resources/catalog/product/threeSixty/99120102140_CSMPossessedOTT2360/01-01.jpg",
                            Image5 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120102140_CSMPossessedStock.jpg",
                            ImageSrc = "https://www.games-workshop.com/resources/catalog/product/920x950/99120102140_CSMPossessedLead.jpg",
                            Name = "Possesed",
                            Price = 45.0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 34,
                            Category = 3,
                            CreatedDate = new DateTime(2022, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All Mekboyz can perform battlefield repairs using no more than a weighty wrench-hammer, a sack of nails and a healthy dose of gumption, but most do their best work in the comfortably anarchic surrounds of their own workshop. Meks are more than capable of cobbling together a workspace from whatever is lying about, with rudimentary workshops springing up from battlefield wreckage even while the bullets are still flying. Greenskin vehicles roar toward such teetering structures, their crews throwing sacks of teef at the resident Mek – he and his crew get to work immediately, sending the Ork customers on their way with snazzier guns, souped-up engines and extra armour plates.\r\n\r\nThis multipart plastic kit contains the components necessary to assemble a Mekboy Workshop. Constructed from metal beams which the industrious Mekboy has salvaged from the clamour of battle around him, the Workshop features a large workbench covered in the gubbinz of his craft – a wall-mounted toolset, an enormous drill, a box of spanners and a vice – and a ton of spare parts. A kustom force field generator, bits of steering wheel, buzzsaw blades; it might look like a random assortment, but the Mekboy who owns it knows exactly where each piece he needs is. A reinforced beam is attached to this workspace at a right angle – a large engine block is hanging from a length of chain, ready for repair or installation, with a large grabbin’ klaw which can be modelled facing in any direction you like. Included are 3 barricades and 3 piles of scrap, which can be placed around the Workshop in any way you like, and the whole kit is compatible with the STC Ryza-pattern Ruins set – build your own kustom sprawling mess!\r\n\r\nThis kit is supplied as 36 components.",
                            Features = "An especially Orky scenery piece, the dominion of a crazed Mekboy\r\nAdds more speed, more rivets and more dakka to Ork vehicles in-game\r\nComplete with 3 sets of barricades and a load of scrap!",
                            Image1 = "https://www.games-workshop.com/resources/catalog/product/threeSixty/99120103109_MekboyWorkshopOTT360/01-01.jpg",
                            Image2 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120103061_OrkMekWorkshop02.jpg",
                            Image3 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120103061_OrkMekWorkshop03.jpg",
                            Image4 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120103061_OrkMekWorkshopTerrain.jpg",
                            Image5 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120103061_OrkMekWorkshop05.jpg",
                            ImageSrc = "https://www.games-workshop.com/resources/catalog/product/920x950/99120103061_OrkMekWorkshop01.jpg",
                            Name = "Mekboy Workshop",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20,
                            Category = 0,
                            CreatedDate = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "As the Indomitus Crusade spreads across the galaxy, the Primaris Space Marines fight battle after battle, becoming hardened veterans of their Chapters. From the mightiest heroes to the staunchest battle-brothers, each is an honoured warrior whose deeds are legend.\r\n\r\nThis set allows you to add new HQ, Elites, and Heavy Support choices to your Space Marines army. A Primaris Chaplain will enhance the fighting strength of the warriors around him, while a Bladeguard Ancient inspires them to fight on against any odds. The Judiciar can be found in the thick of combat, his great blade cleaving enemy heads. Bladeguard Veterans will join him at the vanguard, their storm shields making them an immovable bulwark. Finally, Eradicators will target the enemy's heaviest armour and bring it down in volleys of melta fire.\r\n\r\nThis 64-piece plastic kit builds 9 Space Marines models:\r\n\r\n– 1x Primaris Chaplain\r\n– 1x Judiciar\r\n– 1x Bladeguard Ancient\r\n– 3x Bladeguard Veterans\r\n– 3x Eradicators\r\n\r\nBoth the Bladeguard Veterans and Eradicators include a Sergeant. The set also includes nine 40mm round bases.\r\n\r\nThe models in this set are push-fit and can be assembled without glue. Rules for them can be found in Codex: Space Marines.",
                            Features = "Reinforcements for your Space Marines army Includes three Characters and two squads Available for the first time outside the Indomitus box",
                            Image1 = "https://www.games-workshop.com/resources/catalog/product/threeSixty/99120101353_SMHonouredOfTheChapterOTT8360/01-01.jpg",
                            Image2 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120101353_HonouredoftheChapterFeature2.jpg",
                            Image3 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120101353_HonouredoftheChapterFeature1.jpg",
                            Image4 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120101353_HonouredoftheChapterVeteransFeature.jpg",
                            Image5 = "https://www.games-workshop.com/resources/catalog/product/920x950/99120101353_HonouredoftheChapterSprue.jpg",
                            ImageSrc = "https://www.games-workshop.com/resources/catalog/product/920x950/99120101353_HonouredoftheChapterLead.jpg",
                            Name = "Space Marines: Honoured of the Chapter",
                            Price = 120.0
                        });
                });

            modelBuilder.Entity("GamesWorkshop.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("GamesWorkshop.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("480a013f-9eb1-4890-b543-3fd416466804"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02ddc17d-2187-476b-bda2-eb6b922aee13",
                            Email = "customer@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Patrick",
                            LastName = "Bateman",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@GMAIL.COM",
                            NormalizedUserName = "PATRICK",
                            PasswordHash = "AQAAAAEAACcQAAAAEBEBXjBG2RUvwDtj3d260n8zvYIvGE1v0F4Q1QQrbF25qrDkdXYbOwdjAF3wNWhn7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f40674c2-42dc-4616-ba8c-bf068da86fc5",
                            TwoFactorEnabled = false,
                            UserName = "AmericanPsycho"
                        },
                        new
                        {
                            Id = new Guid("ec274526-d90e-4ecd-bd85-cd84ed7ae0e9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7413657b-acc3-4961-90f4-920eae4994fb",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Paul",
                            LastName = "Allen",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "PAUL",
                            PasswordHash = "AQAAAAEAACcQAAAAEAC3iQm/KDha/Mt1m56nqSyRdyf//g/rZDl+QioyIzgBj++2AYxNRP1av1+vWmuMbA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ccfe79e0-468c-4de2-9e2c-859cd9a75403",
                            TwoFactorEnabled = false,
                            UserName = "PaulAllen"
                        });
                });

            modelBuilder.Entity("GamesWorkshop.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("62b2b25f-a72b-4400-8ef0-4c5aa19f2e24"),
                            Address = "I have no home",
                            Age = 27,
                            Country = "USA",
                            Email = "customer@gmail.com",
                            Name = "Patrick",
                            UserId = new Guid("480a013f-9eb1-4890-b543-3fd416466804")
                        },
                        new
                        {
                            Id = new Guid("ce0c7610-f567-4ce0-b77b-6898ef016696"),
                            Address = "I have no home",
                            Age = 25,
                            Country = "Russia",
                            Email = "admin@gmail.com",
                            Name = "Paul",
                            UserId = new Guid("ec274526-d90e-4ecd-bd85-cd84ed7ae0e9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GamesWorkshop.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("GamesWorkshop.Domain.Entities.User", "User")
                        .WithOne("UserAccount")
                        .HasForeignKey("GamesWorkshop.Domain.Entities.UserAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("GamesWorkshop.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GamesWorkshop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GamesWorkshop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("GamesWorkshop.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesWorkshop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GamesWorkshop.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesWorkshop.Domain.Entities.User", b =>
                {
                    b.Navigation("UserAccount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
